name: Repository CI/CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      generate-coverage: true
      upload-codecov: true
      publish-github-packages: true
    secrets:
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    permissions:
      packages: write
      contents: read

  clean:
    name: "Clean Old Packages"
    needs: pipeline
    uses: ./.github/workflows/clean-packages.yml