name: Clean Old Files

on:
  workflow_dispatch:

  workflow_call:
    
jobs:
  clean:
    runs-on: ubuntu-latest
      
    steps:

    - name: Remove the Old Deveel.Repository.Core Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.Core'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.DynamicLinq Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.DynamicLinq'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.InMemory Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.InMemory'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.MongoFramework Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.MongoFramework'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.EntityFramework Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.EntityFramework'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"


    - name: Remove the Old Deveel.Repository.Manager Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.Manager'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.Manager.DynamicLinq Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.Manager.DynamicLinq'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.Manager.EasyCaching Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.Manager.EasyCaching'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Deveel.Repository.Finbuckle.MultiTenant Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Deveel.Repository.Finbuckle.MultiTenant'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"
