name: Repository PR Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      generate-coverage: false
      upload-codecov: false
    permissions:
        contents: read

