name: Repository Release

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish-to-nuget-org:
        type: boolean
        required: false
        default: false
        description: Publish the generated packages to NuGet.org

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      publish-github-packages: true
      publish-nuget-org: ${{ github.event_name == 'release' || inputs.publish-to-nuget-org }}
    secrets: inherit
    permissions:
      packages: write
      contents: read
