name: "Extract TFM"

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: "The .NET Framework version to extract"
        required: true
        type: string

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Emit .NET 6.0 Framework Version
      if: ${{ inputs.dotnet-version}} == '6.0.x'
      run: echo "DOTNET_FX_VERSION=net6.0" >> $GITHUB_ENV

    - name: Emit .NET 7.0 Framework Version
      if: ${{ inputs.dotnet-version}} == '7.0.x'
      run: echo "DOTNET_FX_VERSION=net7.0" >> $GITHUB_ENV

    - name: Emit .NET 8.0 Framework Version
      if: ${{ inputs.dotnet-version}} == '8.0.x'
      run: echo "DOTNET_FX_VERSION=net8.0" >> $GITHUB_ENV
